server:
  port: 9527
eureka:
  instance:
    hostname: localhost
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: cloud-gateway
  #    开启网关从注册中心发现服务
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          #         lb://CLOUD-PAYMENT-SEVICE        #匹配提供服务的路由地址
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**   #断言,路径相匹配的进行路由转发

        - id: permission_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          #         uri: http://localhost:8001        #匹配提供服务的路由地址
          uri: http://localhost:8003
          predicates:
            - Path=/permission/**   #断言,路径相匹配的进行路由转发
#            - After=2020-11-03T09:50:46.180+08:00[Asia/Shanghai]
#            - Cookie=username,wx
#             #请求头要有X-reqeust-id的属性并且值为整数的正则表达式
        - id: role_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8005
          predicates:
              - Path=/role/**
        - id: rolePermission_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8007
          predicates:
            - Path=/rolePermission/**
        - id: userRole_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8009
          predicates:
            - Path=/userRole/**
        - id: checkPresent_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8011
          predicates:
            - Path=/checkPresence/**
        - id: code_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8013
          predicates:
            - Path=/code/**
        - id: collection_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8015
          predicates:
            - Path=/collection/**
        - id: report_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8017
          predicates:
            - Path=/dailyReport/**
        - id: favor_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8019
          predicates:
            - Path=/favor/**
        - id: group_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8021
          predicates:
            - Path=/group/**
        - id: groupUser_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8023
          predicates:
            - Path=/groupUser/**
        - id: word_routh                 #路由的ID,没有固定的规则但是要求唯一,建议配合服务名
          uri: http://localhost:8025
          predicates:
            - Path=/word/**